# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import faq.models
import formacion.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentesjson',
            name='fuente',
            field=models.ImageField(storage=formacion.ftp.FTPStorage(), upload_to=faq.models.upload_path_handler, verbose_name='Fuente de datos'),
        ),
    ]
